'use client'
import '@styles/globals.css'
import { Inter } from 'next/font/google'
import Nav from '../components/Nav/page'
import { SessionProvider } from 'next-auth/react'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
// 	title: 'LSC-Inspector',
// 	description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<SessionProvider>
					<Nav />
					<main className="app">{children}</main>
				</SessionProvider>
			</body>
		</html>
	)
}
